version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: mysql_container
        restart: always
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_ROOT_PASSWORD: root
        networks:
            - projeto-nis
        ports:
            - "3306:3306"    

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: projeto_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - projeto-nis

    # Symfony apache project container
    www:
        build: docker/php
        container_name: projeto_symfony
        ports:
          - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - projeto-nis

networks:
    projeto-nis:

volumes:
    mysql_data: