index:
    path: /
    controller: App\Controller\CidadaoController::index

pesquisar_formulario:
    path: /pesquisar
    controller: App\Controller\CidadaoController::pesquisar    

cidadao_cadastrar:
    path: /cadastrar
    controller: App\Controller\CidadaoController::cadastrar

pesquisar_post:
    path: /retorno
    controller: App\Controller\CidadaoController::pesquisarPost
    methods: [POST]

